name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.23.0

    - name: Build tesla-control
      run: |
        cd cmd/tesla-control
        env GOOS=linux GOARCH=arm GOARM=7 go build -o tesla_control

    - name: Build tesla-keygen
      run: |
        cd cmd/tesla-keygen
        env GOOS=linux GOARCH=arm GOARM=7 go build -o tesla_keygen

    - name: Upload artifacts
      run: |
        mkdir -p artifacts
        mv cmd/tesla-control/tesla_control artifacts/
        mv cmd/tesla-keygen/tesla_keygen artifacts/

    - name: Test
      run: make test

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: false
        prerelease: false

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/tesla_control
        asset_name: tesla_control
        asset_content_type: application/octet-stream

    - name: Upload Keygen Release Assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./artifacts/tesla_keygen
        asset_name: tesla_keygen
        asset_content_type: application/octet-stream
